controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController


ackermann_steering_controller:
  ros__parameters:
    traction_joints_names:
      - rear_right_wheel_joint
      - rear_left_wheel_joint
    steering_joints_names:
      - front_right_steering_joint
      - front_left_steering_joint

    wheelbase: 0.40
    traction_track_width: 0.34
    steering_track_width: 0.34
    traction_wheels_radius: 0.07

    reference_timeout: 5.0
    open_loop: false
    position_feedback: false
    reduce_wheel_speed_until_steering_reached: true

    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: true
